let acc = document.getElementsByClassName("huaccordion");
let i;

for (i = 0; i < acc.length; i++) {
  acc[i].addEventListener("click", function() {
    this.classList.toggle("active");
    let panel = this.nextElementSibling;
    if (panel.style.maxHeight) {
      panel.style.maxHeight = null;
    } else {
      panel.style.maxHeight = panel.scrollHeight + "px";
    }
  });
}

window.addEventListener("load",(function(){document.getElementById("huflexform").addEventListener("submit",(function(e){e.preventDefault(),M()}));const e=document.getElementById("huflexteksti"),t=document.getElementById("huflexresult"),n=document.getElementById("hulabelheight"),i=document.getElementById("hulabelweight"),m=document.getElementById("huflexbutton");
l=[{minKG:18,maxKG:25,maxCM:117,minCM:102,Flex:10},{minKG:26,maxKG:30,maxCM:122,minCM:116,Flex:20},{minKG:31,maxKG:35,maxCM:117,minCM:110,Flex:20},{minKG:25,maxKG:36,maxCM:135,minCM:123,Flex:20},{minKG:37,maxKG:45,maxCM:124,minCM:110,Flex:30},{minKG:25,maxKG:40,maxCM:154,minCM:135,Flex:30},{minKG:41,maxKG:55,maxCM:135,minCM:116,Flex:40},{minKG:25,maxKG:42,maxCM:161,minCM:142,Flex:40},{minKG:43,maxKG:60,maxCM:142,minCM:123,Flex:50},{minKG:25,maxKG:49,maxCM:174,minCM:150,Flex:50},{minKG:50,maxKG:73,maxCM:150,minCM:123,Flex:55},{minKG:45,maxKG:62,maxCM:181,minCM:158,Flex:65},{minKG:63,maxKG:80,maxCM:158,minCM:135,Flex:65},{minKG:55,maxKG:72,maxCM:187,minCM:168,Flex:70},{minKG:73,maxKG:90,maxCM:168,minCM:149,Flex:70},{minKG:70,maxKG:85,maxCM:187,minCM:169,Flex:75},{minKG:86,maxKG:100,maxCM:171,minCM:155,Flex:75},{minKG:75,maxKG:92,maxCM:200,minCM:178,Flex:85},{minKG:93,maxKG:110,maxCM:178,minCM:155,Flex:85},{minKG:85,maxKG:98,maxCM:200,minCM:179,Flex:95},{minKG:97,maxKG:110,maxCM:181,minCM:162,Flex:95}];
x=document.cookie.split("; ").find((e=>e.startsWith("GBaseConsent=")));let a={fi:{errortext:"Tarkista, että syötetyt tiedot ovat oikein",buttontext:"Suosittele",teksti:"Suositeltu flex:",pituus:"Tarkista pituus",paino:"Tarkista paino",labelheight:"Pituus (cm)",labelweight:"Paino (kg)",notfound:"Ei löytynyt"},en:{errortext:"Please check that the entered information is correct",buttontext:"GO",teksti:"Recommended flex:",pituus:"Check the height",paino:"Check the weight",labelheight:"Height (cm)",labelweight:"Weight (kg)",notfound:"Not found"},ru:{errortext:"Проверьте, что введённые данные верны",buttontext:"Рекомендуйте",teksti:"Рекомендуемая жёсткость (flex):",pituus:"Проверьте рост",paino:"Проверьте вес",labelheight:"Рост (см)",labelweight:"Вес (кг)",notfound:"Не найдено"}};const u=a[document.documentElement.lang||"fi"]||a.fi;n.innerHTML=u.labelheight,i.innerHTML=u.labelweight,e.innerHTML=u.teksti;const o=document.cookie.split("; ").find((e=>e.startsWith("GBaseConsentToAnalytics=")));m&&(m.value=u.buttontext);const h=x;function r(){const e=Number(hu_flex_height.value.trim()),t=Number(hu_flex_weight.value.trim());e<102||e>251||t<18||t>150||e&&t&&M()}function M(){let n=document.getElementById("hu_flex_height"),i=document.getElementById("hu_flex_weight");if(!o)return;if(n=n.value.trim(),i=i.value.trim(),n=Number(n),i=Number(i),h||window.location.replace("https://hockeyunlimited.fi/"),!n||!i)return e.innerHTML=u.teksti,void(t.innerHTML="--");let m=function(e,t){const n=l.length-1;e=Number(e),t=Number(t);let i=[],m=[],x=!1,a=!1;if(!h)return;for(let n of l)if(e>=Number(n.minKG)&&e<=Number(n.maxKG)?(x=!0,i.push(n.Flex)):x=!1,t<=Number(n.maxCM)&&t>=Number(n.minCM)?(a=!0,m.push(n.Flex)):a=!1,x&&a)return Number(n.Flex);let o=i.length,r=m.length,M=0,s=[];M=o<=r?o:r;for(let e=M-1;e>=0;e--)i[e]==m[e]&&s.push(i[e]);if(0==s.length&&(o<=r?s.push(m[0]):s.push(i[0])),i.length>0||m.length>0){if(i.length>m.length)return i[i.length-1];if(i.length<m.length)return m[m.length-1]}if(0==x||0==a)return t<=102?l[0].Flex:t>=200?l[n].Flex:e<=18?l[0].Flex:e>=110?l[n].Flex:u.notfound;if(!x||!a)return s[s.length-1]}(i,n);e.innerHTML=u.teksti,null==m&&(m="--"),t.innerHTML=m}window.top!==window.self&&(window.top.location=window.location),hu_flex_height.addEventListener("input",r),hu_flex_weight.addEventListener("input",r)}));

//FAQ Script End
